#!/bin/bash

# Create txt files with FA value per tracts
# AntCom Left
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Caudate_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Caudate_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_GPe_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_GPe_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_GPi_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_GPi_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_IntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_IntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_IntThalAdh_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_IntThalAdh_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_L_2_Mask_VentPal_mask_L_FA.txt

# AntCom Right
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Caudate_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Caudate_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_GPe_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_GPe_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_GPi_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_GPi_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_IntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_IntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_IntThalAdh_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_IntThalAdh_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_AntCom_mask_R_2_Mask_VentPal_mask_R_FA.txt

# Caudate Left
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_GPe_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_GPe_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_GPi_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_GPi_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_IntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_IntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_IntThalAdh_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_IntThalAdh_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_L_2_Mask_VentPal_mask_L_FA.txt

# Caudate Right
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_GPe_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_GPe_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_GPi_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_GPi_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_IntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_IntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_IntThalAdh_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_IntThalAdh_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Caudate_mask_R_2_Mask_VentPal_mask_R_FA.txt

# GPe Left
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_GPi_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_GPi_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_IntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_IntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_IntThalAdh_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_IntThalAdh_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_L_2_Mask_VentPal_mask_L_FA.txt

# GPe Right
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_GPi_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_GPi_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_IntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_IntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_IntThalAdh_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_IntThalAdh_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPe_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPe_mask_R_2_Mask_VentPal_mask_R_FA.txt

# GPi Left
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_IntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_IntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_IntThalAdh_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_IntThalAdh_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_L_2_Mask_VentPal_mask_L_FA.txt

# GPi Right
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_IntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_IntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_IntThalAdh_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_IntThalAdh_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_GPi_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_GPi_mask_R_2_Mask_VentPal_mask_R_FA.txt

# IntCap Left
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_IntThalAdh_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_IntThalAdh_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_L_2_Mask_VentPal_mask_L_FA.txt

# IntCap Right
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_IntThalAdh_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_IntThalAdh_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntCap_mask_R_2_Mask_VentPal_mask_R_FA.txt

# IntThalAdh Left
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_LocCoer_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_LocCoer_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_L_2_Mask_VentPal_mask_L_FA.txt

# IntThalAdh Right
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_LocCoer_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_LocCoer_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_IntThalAdh_mask_R_2_Mask_VentPal_mask_R_FA.txt

# LocCoer Left
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_Putamen_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_Putamen_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_L_2_Mask_VentPal_mask_L_FA.txt

# LocCoer Right
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_Putamen_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_Putamen_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_LocCoer_mask_R_2_Mask_VentPal_mask_R_FA.txt

# Putamen Left
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_RedNucl_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_RedNucl_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_L_2_Mask_VentPal_mask_L_FA.txt

# Putamen Right
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_RedNucl_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_RedNucl_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Putamen_mask_R_2_Mask_VentPal_mask_R_FA.txt

# RedNucl Left
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_STN_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_STN_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_L_2_Mask_VentPal_mask_L_FA.txt

# RedNucl Right
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_STN_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_STN_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_RedNucl_mask_R_2_Mask_VentPal_mask_R_FA.txt

# STN Left
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_L_2_Mask_SubLentIntCap_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_L_2_Mask_SubLentIntCap_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_L_2_Mask_VentPal_mask_L_FA.txt

# STN Right
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_R_2_Mask_SubLentIntCap_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_R_2_Mask_SubLentIntCap_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_STN_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_STN_mask_R_2_Mask_VentPal_mask_R_FA.txt

# SubLentIntCap Left
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_SubNig_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_SubNig_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_L_2_Mask_VentPal_mask_L_FA.txt

# SubLentIntCap Right
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_SubNig_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_SubNig_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_SubLentIntCap_mask_R_2_Mask_VentPal_mask_R_FA.txt

# SubNig Left
tcksample -stat_tck mean TRACTS_INTER/Mask_SubNig_mask_L_2_Mask_Thalamus_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_SubNig_mask_L_2_Mask_Thalamus_mask_L_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubNig_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_SubNig_mask_L_2_Mask_VentPal_mask_L_FA.txt

# SubNig Right
tcksample -stat_tck mean TRACTS_INTER/Mask_SubNig_mask_R_2_Mask_Thalamus_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_SubNig_mask_R_2_Mask_Thalamus_mask_R_FA.txt
tcksample -stat_tck mean TRACTS_INTER/Mask_SubNig_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_SubNig_mask_R_2_Mask_VentPal_mask_R_FA.txt

# Thalamus Left
tcksample -stat_tck mean TRACTS_INTER/Mask_Thalamus_mask_L_2_Mask_VentPal_mask_L.tck DWI_FA.mif TRACTS_INTER/Mask_Thalamus_mask_L_2_Mask_VentPal_mask_L_FA.txt

# Thalamus Right
tcksample -stat_tck mean TRACTS_INTER/Mask_Thalamus_mask_R_2_Mask_VentPal_mask_R.tck DWI_FA.mif TRACTS_INTER/Mask_Thalamus_mask_R_2_Mask_VentPal_mask_R_FA.txt